### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [ruricolist/random-sample#1]
Building with SBCL 2.1.11.140-4dd1b0aaa / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 4764df9b0ae32c18ac687c873f3f58c1685dfb2a

*random-sample* fails to build with the following error:

```
Unhandled PACKAGE-DOES-NOT-EXIST in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001C24103}>: The name "NAMED-READTABLES" does not designate any package.

```

[Full log here](http://report.quicklisp.org/2021-12-25/failure-report/random-sample.html)

**Comment by ruricolist** [comment]
This should be fixed now.
