### ISSUE TITLE
Sample with replacement larger than sequence

### ISSUE THREAD

**Issue by charJe** [ruricolist/random-sample#2]
I don't see why this should not be allowed. If I'm replacing the elements, then I should never run out of elements. In other words: shouldn't the assertion (https://github.com/ruricolist/random-sample/blob/46b70374ed796b84ea003e83c1db97b0caf97e22/random-sample.lisp#L176) be moved to the else branch (https://github.com/ruricolist/random-sample/blob/46b70374ed796b84ea003e83c1db97b0caf97e22/random-sample.lisp#L183)?

```lisp
(if with-replacement
    (generate-index-array/replacement n len)
    (progn
      (assert (<= n (length seq)))
      (generate-index-array n len)))
```

**Comment by ruricolist** [comment]
I think you're right. If you'd like to make a pull request I'll merge it.

**Comment by jgarte** [comment]
@ruricolist Hi, should this issue be closed?

**Comment by ruricolist** [comment]
Yes, I believe this has been addressed.
